### ISSUE TITLE
Missing template error?

### ISSUE THREAD

**Issue by etcetc** [smartinez87/exception_notification#107] opened 2012-10-25 22:55 UTC
When I just install the app and configure it in my production.rb file per the documentation, I get an exception indicating that it can't find the views(below).  I have included the gem in my Gemfile using:

     gem 'exception_notification', :require => "exception_notifier"

I can address this either by moving the .erb fiels out of the exception_notifier directory directly into views, or else changing line notifier.b:9 to 

      self.append_view_path "#{File.dirname(__FILE__)}/views/exception_notifier"

FATAL: Oct 25 15:16:07: ActionView::MissingTemplate (Missing template /exception_notification with {:locale=>[:en], :formats=>[:text], :handlers=>[:erb, :builder, :voice]}. Searched in:  * "/Users/ff/dev/snapshot/server/app/views"  * "/Users/ff/.rvm/gems/ruby-1.9.3-p194/gems/exception_notification-3.0.0/lib/exception_notifier/views"):  actionpack (3.2.1) lib/action_view/path_set.rb:58:in `find'  actionpack (3.2.1) lib/action_view/lookup_context.rb:109:in `find'  actionpack (3.2.1) lib/action_view/renderer/abstract_renderer.rb:3:in `find_template'  actionpack (3.2.1) lib/action_view/renderer/template_renderer.rb:28:in `determine_template'  actionpack (3.2.1) lib/action_view/renderer/template_renderer.rb:10:in `render'  actionpack (3.2.1) lib/action_view/renderer/renderer.rb:36:in `render_template'  actionpack (3.2.1) lib/action_view/renderer/renderer.rb:17:in `render'  actionpack (3.2.1) lib/abstract_controller/rendering.rb:109:in `_render_template'  actionpack (3.2.1) lib/abstract_controller/rendering.rb:103:in `render_to_body'  actionpack (3.2.1) lib/abstract_controller/rendering.rb:88:in `render'  actionmailer (3.2.1) lib/action_mailer/base.rb:683:in `block in collect_responses_and_parts_order'  actionmailer (3.2.1) lib/action_mailer/collector.rb:26:in `call'  actionmailer (3.2.1) lib/action_mailer/collector.rb:26:in `custom'  actionpack (3.2.1) lib/abstract_controller/collector.rb:10:in `text'  exception_notification (3.0.0) lib/exception_notifier/notifier.rb:160:in `block in compose_email'  actionmailer (3.2.1) lib/action_mailer/base.rb:684:in `collect_responses_and_parts_order'  actionmailer (3.2.1) lib/action_mailer/base.rb:635:in `mail'  exception_notification (3.0.0) lib/exception_notifier/notifier.rb:159:in `compose_email'  exception_notification (3.0.0) lib/exception_notifier/notifier.rb:94:in `exception_notification'  actionpack (3.2.1) lib/abstract_controller/base.rb:167:in `process_action'  actionpack (3.2.1) lib/abstract_controller/base.rb:121:in `process'  actionpack (3.2.1) lib/abstract_controller/rendering.rb:45:in `process'  actionmailer (3.2.1) lib/action_mailer/base.rb:456:in `process'  actionmailer (3.2.1) lib/action_mailer/base.rb:451:in `initialize'  actionmailer (3.2.1) lib/action_mailer/base.rb:438:in `new'  actionmailer (3.2.1) lib/action_mailer/base.rb:438:in `method_missing'  exception_notification (3.0.0) lib/exception_notifier.rb:48:in `rescue in call'  exception_notification (3.0.0) lib/exception_notifier.rb:40:in `call'  actionpack (3.2.1) lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'  rack (1.4.1) lib/rack/etag.rb:23:in `call'  rack (1.4.1) lib/rack/conditionalget.rb:25:in `call'  actionpack (3.2.1) lib/action_dispatch/middleware/head.rb:14:in `call'  actionpack (3.2.1) lib/action_dispatch/middleware/params_parser.rb:21:in `call'  actionpack (3.2.1) lib/action_dispatch/middleware/flash.rb:242:in `call'  rack (1.4.1) lib/rack/session/abstract/id.rb:205:in `context'  rack (1.4.1) lib/rack/session/abstract/id.rb:200:in `call'  actionpack (3.2.1) lib/action_dispatch/middleware/cookies.rb:338:in `call'  activerecord (3.2.1) lib/active_record/query_cache.rb:64:in `call'  activerecord (3.2.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:443:in `call'  actionpack (3.2.1) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'  activesupport (3.2.1) lib/active_support/callbacks.rb:405:in `_run__2271857228730812799__call__3278409340782142530__callbacks'  activesupport (3.2.1) lib/active_support/callbacks.rb:405:in `__run_callback'  activesupport (3.2.1) lib/active_support/callbacks.rb:385:in `_run_call_callbacks'  activesupport (3.2.1) lib/active_support/callbacks.rb:81:in `run_callbacks'  actionpack (3.2.1) lib/action_dispatch/middleware/callbacks.rb:27:in `call'  actionpack (3.2.1) lib/action_dispatch/middleware/remote_ip.rb:31:in `call'  actionpack (3.2.1) lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'  actionpack (3.2.1) lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'  /Users/ff/.rvm/gems/ruby-1.9.3-p194/bundler/gems/npb_logging-e487a1cabd55/lib/npb_logging/rails_ext/rack/logger.rb:13:in `call_app'  railties (3.2.1) lib/rails/rack/logger.rb:16:in `call'  actionpack (3.2.1) lib/action_dispatch/middleware/request_id.rb:22:in `call'  rack (1.4.1) lib/rack/methodoverride.rb:21:in `call'  rack (1.4.1) lib/rack/runtime.rb:17:in `call'  activesupport (3.2.1) lib/active_support/cache/strategy/local_cache.rb:72:in `call'  rack (1.4.1) lib/rack/lock.rb:15:in `call'  rack-cache (1.2) lib/rack/cache/context.rb:136:in `forward'  rack-cache (1.2) lib/rack/cache/context.rb:245:in `fetch'  rack-cache (1.2) lib/rack/cache/context.rb:185:in `lookup'  rack-cache (1.2) lib/rack/cache/context.rb:66:in `call!'  rack-cache (1.2) lib/rack/cache/context.rb:51:in `call'  railties (3.2.1) lib/rails/engine.rb:479:in `call'  railties (3.2.1) lib/rails/application.rb:220:in `call'  rack (1.4.1) lib/rack/content_length.rb:14:in `call'  railties (3.2.1) lib/rails/rack/log_tailer.rb:14:in `call'  rack (1.4.1) lib/rack/handler/webrick.rb:59:in `service'  /Users/ff/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/webrick/httpserver.rb:138:in `service'  /Users/ff/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/webrick/httpserver.rb:94:in `run'  /Users/ff/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/webrick/server.rb:191:in `block in start_thread'

**Comment by robyoder** [comment] 2015-02-06 01:24
I'm still experiencing this issue, same project as @jxpx777, and now his fix he posted on SO doesn't work because of gem restructuring. Rails 3.2, Ruby 1.9.3, exception_notification 4.0.1

**Comment by robyoder** [comment] 2015-02-06 01:25
I can fix it by modifying the gem files themselves to include the `/exception_notifier` directory in the view path, but not otherwise.

**Comment by robyoder** [comment] 2015-02-06 01:29
One last note, I can also get rid of the issue by changing `config.cache_classes = true` to `false` in my environment config file.

**Comment by san650** [comment] 2015-12-08 23:33
@robyoder Can you upload an example application where this error is happening?

**Comment by robyoder** [comment] 2015-12-09 02:06
Oh man, this feels like ages ago. I'll make a note to take a look, but I don't think I have time to make a sample app right now. We obviously solved it one way or another, so I'll have to search through the git history to figure out what we did.

**Comment by san650** [comment] 2015-12-14 21:47
Hi!

I'm doing some bug triage and I would like to know if this bug is still happening on master.

The idea is to close those errors that can't be reproduced or that don't have enough information to reproduce it. I'll revisit this bug in a week and I'll close it if there's no more information. It can be opened again later if necessary.

Thanks!

**Closed** 2015-12-19 18:45 UTC
