### ISSUE TITLE
Exception Notification doesn't seem to work with the Better Errors gem

### ISSUE THREAD

**Issue by marcamillion** [smartinez87/exception_notification#122] opened 2013-02-07 09:30 UTC
This is the first time I am trying out exception_notification and I have done everything per the Railscast and it isn't working.

The only difference I have is that I am using the better_errors gem and in my log file, I see one call to `exception_notifier` and it seems to be getting lost in the sea of everything else happening.

    Started GET "/" for 127.0.0.1 at 2013-02-07 04:21:56 -0500
    Processing by HomeController#index as HTML
      User Load (1.0ms)  SELECT "users".* FROM "users" 
      Rendered home/index.html.erb within layouts/application (9.7ms)
    Completed 500 Internal Server Error in 290ms

    NoMethodError - undefined method `titl' for nil:NilClass:
      app/views/home/index.html.erb:18:in `#<Class:0x007fc2f36d0228>#_app_views_home_index_html_erb___4355210907402428866_70237625134460'
      (gem) actionpack-3.2.11/lib/action_view/template.rb:145:in `block in ActionView::Template#render'
      (gem) activesupport-3.2.11/lib/active_support/notifications.rb:123:in `block in ActiveSupport::Notifications.instrument'
      (gem) activesupport-3.2.11/lib/active_support/notifications/instrumenter.rb:20:in `ActiveSupport::Notifications::Instrumenter#instrument'
      (gem) activesupport-3.2.11/lib/active_support/notifications.rb:123:in `ActiveSupport::Notifications.instrument'
      (gem) actionpack-3.2.11/lib/action_view/template.rb:143:in `ActionView::Template#render'
      (gem) actionpack-3.2.11/lib/action_view/renderer/template_renderer.rb:47:in `block (2 levels) in ActionView::TemplateRenderer#render_template'
      (gem) actionpack-3.2.11/lib/action_view/renderer/abstract_renderer.rb:38:in `block in ActionView::TemplateRenderer#instrument'
      (gem) activesupport-3.2.11/lib/active_support/notifications.rb:123:in `block in ActiveSupport::Notifications.instrument'
      (gem) activesupport-3.2.11/lib/active_support/notifications/instrumenter.rb:20:in `ActiveSupport::Notifications::Instrumenter#instrument'
      (gem) activesupport-3.2.11/lib/active_support/notifications.rb:123:in `ActiveSupport::Notifications.instrument'
      (gem) actionpack-3.2.11/lib/action_view/renderer/abstract_renderer.rb:38:in `ActionView::TemplateRenderer#instrument'
      (gem) actionpack-3.2.11/lib/action_view/renderer/template_renderer.rb:46:in `block in ActionView::TemplateRenderer#render_template'
      (gem) actionpack-3.2.11/lib/action_view/renderer/template_renderer.rb:54:in `ActionView::TemplateRenderer#render_with_layout'
      (gem) actionpack-3.2.11/lib/action_view/renderer/template_renderer.rb:45:in `ActionView::TemplateRenderer#render_template'
      (gem) actionpack-3.2.11/lib/action_view/renderer/template_renderer.rb:18:in `ActionView::TemplateRenderer#render'
      (gem) actionpack-3.2.11/lib/action_view/renderer/renderer.rb:36:in `ActionView::Renderer#render_template'
      (gem) actionpack-3.2.11/lib/action_view/renderer/renderer.rb:17:in `ActionView::Renderer#render'
      (gem) actionpack-3.2.11/lib/abstract_controller/rendering.rb:110:in `HomeController#_render_template'
      (gem) actionpack-3.2.11/lib/action_controller/metal/streaming.rb:225:in `HomeController#_render_template'
      (gem) actionpack-3.2.11/lib/abstract_controller/rendering.rb:103:in `HomeController#render_to_body'
      (gem) actionpack-3.2.11/lib/action_controller/metal/renderers.rb:28:in `HomeController#render_to_body'
      (gem) actionpack-3.2.11/lib/action_controller/metal/compatibility.rb:50:in `HomeController#render_to_body'
      (gem) actionpack-3.2.11/lib/abstract_controller/rendering.rb:88:in `HomeController#render'
      (gem) actionpack-3.2.11/lib/action_controller/metal/rendering.rb:16:in `HomeController#render'
      (gem) actionpack-3.2.11/lib/action_controller/metal/instrumentation.rb:40:in `block (2 levels) in HomeController#render'
      (gem) activesupport-3.2.11/lib/active_support/core_ext/benchmark.rb:5:in `block in Benchmark.ms'
      /.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/benchmark.rb:295:in `Benchmark.realtime'
      (gem) activesupport-3.2.11/lib/active_support/core_ext/benchmark.rb:5:in `Benchmark.ms'
      (gem) actionpack-3.2.11/lib/action_controller/metal/instrumentation.rb:40:in `block in HomeController#render'
      (gem) actionpack-3.2.11/lib/action_controller/metal/instrumentation.rb:83:in `HomeController#cleanup_view_runtime'
      (gem) activerecord-3.2.11/lib/active_record/railties/controller_runtime.rb:24:in `HomeController#cleanup_view_runtime'
      (gem) actionpack-3.2.11/lib/action_controller/metal/instrumentation.rb:39:in `HomeController#render'
      (gem) remotipart-1.0.2/lib/remotipart/render_overrides.rb:8:in `HomeController#render'
      (gem) actionpack-3.2.11/lib/action_controller/metal/implicit_render.rb:10:in `HomeController#default_render'
      (gem) actionpack-3.2.11/lib/action_controller/metal/implicit_render.rb:5:in `HomeController#send_action'
      (gem) actionpack-3.2.11/lib/abstract_controller/base.rb:167:in `HomeController#process_action'
      (gem) actionpack-3.2.11/lib/action_controller/metal/rendering.rb:10:in `HomeController#process_action'
      (gem) actionpack-3.2.11/lib/abstract_controller/callbacks.rb:18:in `block in HomeController#process_action'
      (gem) activesupport-3.2.11/lib/active_support/callbacks.rb:425:in `HomeController#_run__3674050067414519199__process_action__315436307929532323__callbacks'
      (gem) activesupport-3.2.11/lib/active_support/callbacks.rb:405:in `HomeController.__run_callback'
      (gem) activesupport-3.2.11/lib/active_support/callbacks.rb:385:in `HomeController#_run_process_action_callbacks'
      (gem) activesupport-3.2.11/lib/active_support/callbacks.rb:81:in `HomeController#run_callbacks'
      (gem) actionpack-3.2.11/lib/abstract_controller/callbacks.rb:17:in `HomeController#process_action'
      (gem) actionpack-3.2.11/lib/action_controller/metal/rescue.rb:29:in `HomeController#process_action'
      (gem) actionpack-3.2.11/lib/action_controller/metal/instrumentation.rb:30:in `block in HomeController#process_action'
      (gem) activesupport-3.2.11/lib/active_support/notifications.rb:123:in `block in ActiveSupport::Notifications.instrument'
      (gem) activesupport-3.2.11/lib/active_support/notifications/instrumenter.rb:20:in `ActiveSupport::Notifications::Instrumenter#instrument'
      (gem) activesupport-3.2.11/lib/active_support/notifications.rb:123:in `ActiveSupport::Notifications.instrument'
      (gem) actionpack-3.2.11/lib/action_controller/metal/instrumentation.rb:29:in `HomeController#process_action'
      (gem) actionpack-3.2.11/lib/action_controller/metal/params_wrapper.rb:207:in `HomeController#process_action'
      (gem) activerecord-3.2.11/lib/active_record/railties/controller_runtime.rb:18:in `HomeController#process_action'
      (gem) actionpack-3.2.11/lib/abstract_controller/base.rb:121:in `HomeController#process'
      (gem) actionpack-3.2.11/lib/abstract_controller/rendering.rb:45:in `HomeController#process'
      (gem) actionpack-3.2.11/lib/action_controller/metal.rb:203:in `HomeController#dispatch'
      (gem) actionpack-3.2.11/lib/action_controller/metal/rack_delegation.rb:14:in `HomeController#dispatch'
      (gem) actionpack-3.2.11/lib/action_controller/metal.rb:246:in `block in HomeController.action'
      (gem) actionpack-3.2.11/lib/action_dispatch/routing/route_set.rb:73:in `ActionDispatch::Routing::RouteSet::Dispatcher#dispatch'
      (gem) actionpack-3.2.11/lib/action_dispatch/routing/route_set.rb:73:in `ActionDispatch::Routing::RouteSet::Dispatcher#call'
      (gem) actionpack-3.2.11/lib/action_dispatch/routing/route_set.rb:36:in `Journey::Router#call'
      (gem) journey-1.0.4/lib/journey/router.rb:68:in `block in Journey::Router#call'
      (gem) journey-1.0.4/lib/journey/router.rb:56:in `ActionDispatch::Routing::RouteSet#call'
      (gem) journey-1.0.4/lib/journey/router.rb:56:in `Rack::Pjax#call'
      (gem) actionpack-3.2.11/lib/action_dispatch/routing/route_set.rb:601:in `MetaRequest::Middlewares::AppRequestHandler#call'
      (gem) rack-pjax-0.6.0/lib/rack/pjax.rb:12:in `Rack::ResponseHeaders#call'
      (gem) meta_request-0.2.1/lib/meta_request/middlewares/app_request_handler.rb:11:in `MetaRequest::Middlewares::Headers#call'
      (gem) rack-contrib-1.1.0/lib/rack/contrib/response_headers.rb:17:in `MetaRequest::Middlewares::MetaRequestHandler#call'
      (gem) meta_request-0.2.1/lib/meta_request/middlewares/headers.rb:16:in `BetterErrors::Middleware#app_call'
      (gem) meta_request-0.2.1/lib/meta_request/middlewares/meta_request_handler.rb:13:in `BetterErrors::Middleware#call'
      (gem) better_errors-0.0.8/lib/better_errors/middleware.rb:20:in `ExceptionNotifier#call'
      (gem) better_errors-0.0.8/lib/better_errors/middleware.rb:14:in `Warden::Manager#call'
      (gem) exception_notification-3.0.1/lib/exception_notifier.rb:41:in `Warden::Manager#call'
      (gem) warden-1.2.1/lib/warden/manager.rb:35:in `block in ActionDispatch::BestStandardsSupport#call'
      (gem) warden-1.2.1/lib/warden/manager.rb:34:in `Rack::ETag#call'
      (gem) warden-1.2.1/lib/warden/manager.rb:34:in `Rack::ConditionalGet#call'
      (gem) actionpack-3.2.11/lib/action_dispatch/middleware/best_standards_support.rb:17:in `ActionDispatch::Head#call'
      (gem) rack-1.4.3/lib/rack/etag.rb:23:in `Remotipart::Middleware#call'
      (gem) rack-1.4.3/lib/rack/conditionalget.rb:25:in `ActionDispatch::ParamsParser#call'
      (gem) actionpack-3.2.11/lib/action_dispatch/middleware/head.rb:14:in `ActionDispatch::Flash#call'
      (gem) remotipart-1.0.2/lib/remotipart/middleware.rb:30:in `ActionDispatch::Session::CookieStore#context'
      (gem) actionpack-3.2.11/lib/action_dispatch/middleware/params_parser.rb:21:in `ActionDispatch::Session::CookieStore#call'
      (gem) actionpack-3.2.11/lib/action_dispatch/middleware/flash.rb:242:in `ActionDispatch::Cookies#call'
      (gem) rack-1.4.3/lib/rack/session/abstract/id.rb:210:in `ActiveRecord::QueryCache#call'
      (gem) rack-1.4.3/lib/rack/session/abstract/id.rb:205:in `ActiveRecord::ConnectionAdapters::ConnectionManagement#call'
      (gem) actionpack-3.2.11/lib/action_dispatch/middleware/cookies.rb:341:in `ActionDispatch::Callbacks#call'
      (gem) activerecord-3.2.11/lib/active_record/query_cache.rb:64:in `ActionDispatch::Callbacks#_run__2957214149775995846__call__2010541572530361835__callbacks'
      (gem) activerecord-3.2.11/lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in `ActionDispatch::Callbacks.__run_callback'
      (gem) actionpack-3.2.11/lib/action_dispatch/middleware/callbacks.rb:28:in `block in ActionDispatch::Callbacks#_run_call_callbacks'
      (gem) activesupport-3.2.11/lib/active_support/callbacks.rb:405:in `ActionDispatch::Callbacks#run_callbacks'
      (gem) activesupport-3.2.11/lib/active_support/callbacks.rb:405:in `ActionDispatch::Callbacks#call'
      (gem) activesupport-3.2.11/lib/active_support/callbacks.rb:385:in `ActionDispatch::Reloader#call'
      (gem) activesupport-3.2.11/lib/active_support/callbacks.rb:81:in `ActionDispatch::RemoteIp#call'
      (gem) actionpack-3.2.11/lib/action_dispatch/middleware/callbacks.rb:27:in `ActionDispatch::DebugExceptions#call'
      (gem) actionpack-3.2.11/lib/action_dispatch/middleware/reloader.rb:65:in `ActionDispatch::ShowExceptions#call'
      (gem) actionpack-3.2.11/lib/action_dispatch/middleware/remote_ip.rb:31:in `Rails::Rack::Logger#call_app'
      (gem) actionpack-3.2.11/lib/action_dispatch/middleware/debug_exceptions.rb:16:in `Rails::Rack::Logger#call'
      (gem) actionpack-3.2.11/lib/action_dispatch/middleware/show_exceptions.rb:56:in `ActiveSupport::TaggedLogging#tagged'
      (gem) railties-3.2.11/lib/rails/rack/logger.rb:32:in `Rails::Rack::Logger#call'
      (gem) railties-3.2.11/lib/rails/rack/logger.rb:16:in `block in Rails::Rack::Logger#call_with_quiet_assets'
      (gem) activesupport-3.2.11/lib/active_support/tagged_logging.rb:22:in `ActionDispatch::RequestId#call'
      (gem) railties-3.2.11/lib/rails/rack/logger.rb:16:in `Rack::MethodOverride#call'
      (gem) quiet_assets-1.0.1/lib/quiet_assets.rb:20:in `Rack::Runtime#call'
      (gem) actionpack-3.2.11/lib/action_dispatch/middleware/request_id.rb:22:in `ActiveSupport::Cache::Strategy::LocalCache::Middleware#call'
      (gem) rack-1.4.3/lib/rack/methodoverride.rb:21:in `Rack::Lock#call'
      (gem) rack-1.4.3/lib/rack/runtime.rb:17:in `ActionDispatch::Static#call'
      (gem) activesupport-3.2.11/lib/active_support/cache/strategy/local_cache.rb:72:in `RealtyCloud::Application#call'
      (gem) rack-1.4.3/lib/rack/lock.rb:15:in `RealtyCloud::Application#call'
      (gem) actionpack-3.2.11/lib/action_dispatch/middleware/static.rb:62:in `Rack::ContentLength#call'
      (gem) railties-3.2.11/lib/rails/engine.rb:479:in `Rails::Rack::LogTailer#call'
      (gem) railties-3.2.11/lib/rails/application.rb:223:in `Thin::Connection#pre_process'
      (gem) rack-1.4.3/lib/rack/content_length.rb:14:in `Thin::Connection#pre_process'
      (gem) railties-3.2.11/lib/rails/rack/log_tailer.rb:17:in `Thin::Connection#process'
      (gem) thin-1.5.0/lib/thin/connection.rb:81:in `block in Thin::Connection#receive_data'
      (gem) thin-1.5.0/lib/thin/connection.rb:79:in `EventMachine.run'
      (gem) thin-1.5.0/lib/thin/connection.rb:79:in `Thin::Backends::TcpServer#start'
      (gem) thin-1.5.0/lib/thin/connection.rb:54:in `Thin::Server#start'
      (gem) thin-1.5.0/lib/thin/connection.rb:39:in `Rack::Handler::Thin.run'
      (gem) eventmachine-1.0.0/lib/eventmachine.rb:187:in `Rails::Server#start'
      (gem) eventmachine-1.0.0/lib/eventmachine.rb:187:in `Rails::Server#start'
      (gem) thin-1.5.0/lib/thin/backends/base.rb:63:in `start'
      (gem) thin-1.5.0/lib/thin/server.rb:159:in `start'
      (gem) rack-1.4.3/lib/rack/handler/thin.rb:13:in `run'
      (gem) rack-1.4.3/lib/rack/server.rb:268:in `start'
      (gem) railties-3.2.11/lib/rails/commands/server.rb:70:in `start'
      (gem) railties-3.2.11/lib/rails/commands.rb:55:in `block in <top (required)>'
      (gem) railties-3.2.11/lib/rails/commands.rb:50:in `tap'
      (gem) railties-3.2.11/lib/rails/commands.rb:50:in `<top (required)>'
      script/rails:6:in `require'
      script/rails:6:in `<main>'

    Started POST "/__better_errors/70237648020860/variables" for 127.0.0.1 at 2013-02-07 04:22:12 -0500

It's a bit hard to spot there, but it's in the middle...here I have pulled it out:

      (gem) meta_request-0.2.1/lib/meta_request/middlewares/meta_request_handler.rb:13:in `BetterErrors::Middleware#call'
      (gem) better_errors-0.0.8/lib/better_errors/middleware.rb:20:in `ExceptionNotifier#call'
      (gem) better_errors-0.0.8/lib/better_errors/middleware.rb:14:in `Warden::Manager#call'
      (gem) exception_notification-3.0.1/lib/exception_notifier.rb:41:in `Warden::Manager#call'
      (gem) warden-1.2.1/lib/warden/manager.rb:35:in `block in ActionDispatch::BestStandardsSupport#call'
      (gem) warden-1.2.1/lib/warden/manager.rb:34:in `Rack::ETag#call'
      (gem) warden-1.2.1/lib/warden/manager.rb:34:in `Rack::ConditionalGet#call'

Is this issue one you guys are aware of?

Thanks.

**Comment by san650** [comment] 2015-12-08 23:54
@marcamillion Just an idea, did you tried to change the order of the middlewares? I think the problem is that the BetterErrors middleware catches the exception and doesn't throw it again so ExceptionNotifications never sees it.

Maybe you can try to use `config.middleware.insert_after` to reverse the order in which ExceptionNotification and BetterErrors are called.

http://guides.rubyonrails.org/rails_on_rack.html#configuring-middleware-stack

**Comment by san650** [comment] 2015-12-14 21:48
Hi!

I'm doing some bug triage and I would like to know if this bug is still happening on master.

The idea is to close those errors that can't be reproduced or that don't have enough information to reproduce it. I'll revisit this bug in a week and I'll close it if there's no more information. It can be opened again later if necessary.

Thanks!

**Closed** 2015-12-19 18:47 UTC
