### ISSUE TITLE
Data section not added in some case

### ISSUE THREAD

**Issue by herbertia** [smartinez87/exception_notification#211] opened 2014-02-06 17:05 UTC
Hi,

We are running on rails 4 with exception_notifier 4.0.0.
We have added a before_action in ApplicationController to add additional data to the emails notification. It works perfectly except for one exception: InvalidAuthenticityToken.
We are trying to track why this error is happening and where but with this kind of Exception we do not have neither the backtrace section nor the data section.
Is it normal or do we have to do something special for this kind of exception?

Thanks for your help.

**Comment by Kriechi** [comment] 2015-01-28 14:35
same here... no solution yet.

**Comment by betesh** [comment] 2015-10-14 15:02
backtrace is missing because the BacktraceCleaner filter removed all rows of the backtrace.  See https://github.com/smartinez87/exception_notification/blob/v4.1.1/lib/exception_notifier/email_notifier.rb#L33

data is missing because it's only when you put something in `env['exception_notifier.exception_data']` or passed a `data` argument to `notify_exception`.

**Comment by betesh** [comment] 2015-10-16 14:03
Not sure if this is the place for this discussion, but I wonder if InvalidAuthenticityToken exceptions should be ignored by exception_notification.  It's an error caused by the user, that the user can recover from by refreshing the page.  On the other hand, if you're going to ignore those errors and just ask the user to reload the page, that might be the equivalent of `protect`ing`_from_forgery with: :null_session`, so you may as well just configure it that way instead.

**Comment by san650** [comment] 2015-12-14 22:06
Hi!

I'm doing some bug triage and I would like to know if this bug is still happening on master.

The idea is to close those errors that can't be reproduced or that don't have enough information to reproduce it. I'll revisit this bug in a week and I'll close it if there's no more information. It can be opened again later if necessary.

Thanks!

**Comment by betesh** [comment] 2015-12-15 00:19
@san650 See my comment above.  It's not really a bug in the code--more just a question of making the code match people's expectations.  My suggestion is to document in the README that the gem doesn't add a data section unless there is data to describe there.

**Comment by san650** [comment] 2015-12-15 00:34
@betesh thanks for you answer, can you open a PR with this suggestion?

**Comment by wanqizhu** [comment] 2017-03-04 17:50
@san650 Hi, I'm just following the README now and adding data to `request.env["exception_notifier.exception_data"]`

But the data (current_user) is still not send in the emails. I'm using default sections and everything else is the default setup -- any idea why this might be happening?

Thanks!

**Comment by san650** [comment] 2017-03-04 21:16
@wanqizhu we need a bit more info about your setup. What versions of exception_notification and rails are you using? Can you share your exception_notification configuration?

Maybe @smartinez87 have more insight about this issue.

**Comment by wanqizhu** [comment] 2017-03-04 23:19
I'm using the newest gem version 4.2.1, and rails 4.2.0. Here's my configuration:

`  # https://github.com/smartinez87/exception_notification
  Rails.application.config.middleware.use ExceptionNotification::Rack,
  :email => {
    :ignore_exceptions => ['ActiveRecord::RecordNotUnique', 'ActionController::InvalidAuthenticityToken'] + ExceptionNotifier.ignored_exceptions,
    :ignore_crawlers => %w{Googlebot bingbot},

    :deliver_with => :deliver, # Rails >= 4.2.1 do not need this option since it defaults to :deliver_now
    :email_prefix => "[WF Exception] ",
    :sender_address => %{"rails exception_notification" <notifier@example.com>},
    :exception_recipients => %w{wanqi.zhu@willowflare.com},
    :normalize_subject => true
  }`

Do I need to add anything to the :sections variable or?

**Comment by Revinand** [comment] 2018-02-26 14:36
InvalidAuthenticityToken exception is produced by rails RequestForgeryProtection class, which is enabled by adding `protect_from_forgery with: :exception` callback at the beginning of ApplicationController. In Rails 4 this callback is invoked at the first place regardless you put anything before it.

One workaround is to override `handle_unverified_request` method in the ApplicationController and call your method which adds necessary data to a notification there:

```
class ApplicationController
  protect_from_forgery with: :exception

  before_action :prepare_exception_notifier

  private

  def prepare_exception_notifier
    # your data goes here
  end

  def handle_unverified_request
    prepare_exception_notifier
    super
  end
end
```

**Comment by EmilioCristalli** [comment] 2019-04-20 18:50
@herbertia regarding the missing `data`, as @Revinand  mentioned, i think the problem is that the code to protect from request forgery is executed before your `before_filter` is called. Therefore `env['exception_notifier.exception_data']` is not populated.

A possible workaround for this might be to use `prepend_before_action`, so that your function is executed first in the callbacks chain, before the code that checks for request forgery.


Regarding the backtrace, as @betesh mentioned, it is probably empty because of the clean backtrace feature. Since the exception is generated in Rails, and there is nothing from your own app in the backtrace, everything is filtered


Feel free to reopen if this is still an issue

**Closed by EmilioCristalli** 2019-04-20 18:50 UTC
