### ISSUE TITLE
Can not make it work with sidekiq

### ISSUE THREAD

**Issue by fabrouy** [smartinez87/exception_notification#261] opened 2015-02-14 23:22 UTC
Hey!

Before anything thanks for builing this awesome library and grettings from UY.
This is my initializer:

``` ruby
require 'exception_notification/rails'
require 'exception_notification/sidekiq'

ExceptionNotification.configure do |config|
  config.add_notifier :email, {
    :email_prefix         => "xxxxxxxx",
    :sender_address       => %{xxxxxxxx},
    :exception_recipients => %w{yyyyyyyy},
    :ignore_crawlers      => %w{Googlebot bingbot}
  }
end
```

Then I'm doing:

``` ruby
ExceptionNotifier.notify_exception(exception,
   env: request.env, data: { message: "xxxxxxxxx", foo: "bar" }
)
```

Mails do not get sent using sidekiq but standard sender.

I'm using Rails 4.0.3 , Sidekiq 3.3.1 and Redis 2.8.19.

Am I missing something? Thanks!

**Comment by lucianosousa** [comment] 2015-02-15 01:32
which ruby version are you using?
specs for this setup with ruby 1.9.3 are broke.
I suggest you migrate to ruby 2.x

**Comment by fabrouy** [comment] 2015-02-15 02:08
ruby 2.1.2p95 (2014-05-08 revision 45877) [x86_64-linux]

**Comment by dmagliola** [comment] 2015-02-15 10:12
Are you trying to capture errors that happen on Sidekiq jobs, and get them e-mailed to you?
Or are you trying to get the error e-mails that happen in your web app sent to you using a Sidekiq job, instead of in real-time?

I believe exception_notifier doesn't support the second use case (yet, hopefully), only the first one.

**Comment by blakeperdue** [comment] 2015-07-29 15:30
@dmagliola How do you do the first one (get errors that happen on Sidekiq jobs emailed to you)? Is there any special configuration necessary to make this happen.

**Comment by dmagliola** [comment] 2015-07-29 16:51
I'm not 100% sure, because I did this many months ago. I remember it was quite easy, though...

This is what I can find in my codebase: In the initializer where you set up exception_notification, add this require:

    require 'exception_notification/sidekiq'

That's all I can see that seems special to sidekiq.

**Comment by blakeperdue** [comment] 2015-07-29 16:56
Great, thanks @dmagliola

**Comment by san650** [comment] 2015-12-14 22:15
Hi!

I'm doing some bug triage and I would like to know if this bug is still happening on master.

The idea is to close those errors that can't be reproduced or that don't have enough information to reproduce it. I'll revisit this bug in a week and I'll close it if there's no more information. It can be opened again later if necessary.

Thanks!

**Comment by blakeperdue** [comment] 2015-12-14 22:17
It works for me using @dmagliola 's solution:
`require 'exception_notification/sidekiq'`

**Comment by nk-mandilwar** [comment] 2017-05-19 11:38
ExceptionNotifier is not sending mail from production, though I can see mail being sent in the log, but it is not reaching to me. When I tried to send mail from console inside server using ExceptionNotifier, I am receiving mail. 
Please help me!

**Comment by smartinez87** [comment] 2017-05-19 14:25
@nk-mandilwar can you please provide a little more detail to better help you? Are you sure it's not a config issue with your production env? Are you getting any other emails from production?

**Comment by nk-mandilwar** [comment] 2017-05-19 19:45
@smartinez87 I don't think it should be config problem, otherwise exception notification couldn't be sent from rails console in the server computer. Moreover, mail is sent in development environment. 
Is there anything I am missing in production?

**Comment by blakeperdue** [comment] 2017-05-19 19:50
@nk-mandilwar is your production system sending other emails out successfully?

**Comment by nk-mandilwar** [comment] 2017-05-19 19:51
@blakeperdue Yes.

**Comment by blakeperdue** [comment] 2017-05-19 19:54
Thought so, very odd. 

Are you including `require 'exception_notification/sidekiq'` in all your workers or mailers? I think that's the thing I missed. Although in my case, I didn't have it working on DEV like you currently do, so you're problem sounds very strange.

**Comment by nk-mandilwar** [comment] 2017-05-19 19:55
I am not using that as I am not sending exception emails from worker

**Comment by nk-mandilwar** [comment] 2017-05-19 20:03
Is there any time out for sending emails in rails?

**Comment by FLarra** [comment] 2018-12-15 04:51
I know it's been a while since the last activity so I'd like to take some action here.

Is this still an issue? Is there any conclusion or update about it? Can we mark it as resolved or need some work on it?

@nk-mandilwar @fabrouy 

Thanks

**Comment by FLarra** [comment] 2019-01-24 13:05
Closing it now. Please reopen it if you consider so.

**Closed by FLarra** 2019-01-24 13:05 UTC
