### ISSUE TITLE
Dependency Conflict w/ Capybara

### ISSUE THREAD

**Issue by null-null-null** [smartinez87/exception_notification#207] opened 2014-01-06 19:09 UTC
In my gemfile, I can bundle either exception_notification or capybara. Unfortunately, when I try bundling both, I get this dependency conflict:

    Bundler could not find compatible versions for gem "mime-types":
      In Gemfile:
        exception_notification (~> 4.0.1) ruby depends on
          mime-types (~> 1.16) ruby

        capybara (>= 0) ruby depends on
          mime-types (2.0)

    Bundler could not find compatible versions for gem "actionpack":
      In Gemfile:
        coffee-rails (>= 0) ruby depends on
          actionpack (= 3.2.0) ruby

        jquery-fileupload-rails (>= 0) ruby depends on
          actionpack (4.0.0)

    Bundler could not find compatible versions for gem "activesupport":
      In Gemfile:
        friendly_id (~> 5.0.0) ruby depends on
          activesupport (= 4.0.0) ruby

        exception_notification (~> 4.0.1) ruby depends on
          activesupport (3.0.4)

**Comment by san650** [comment] 2015-12-14 22:03
Hi!

I'm doing some bug triage and I would like to know if this bug is still happening on master.

The idea is to close those errors that can't be reproduced or that don't have enough information to reproduce it. I'll revisit this bug in a week and I'll close it if there's no more information. It can be opened again later if necessary.

Thanks!

**Comment by jarrett** [comment] 2015-12-15 18:14
It's been a year since I encountered this error. From my perspective, it seems to have resolved itself.

**Closed** 2015-12-19 18:56 UTC
