### ISSUE TITLE
  incompatible character encodings: ASCII-8BIT and UTF-8

### ISSUE THREAD

**Issue by biadoo** [smartinez87/exception_notification#102] opened 2012-10-16 09:20 UTC
Error still present in 3.0.0.rc1:

An Encoding::CompatibilityError occurred in companies#index:

  incompatible character encodings: ASCII-8BIT and UTF-8
  vendor/bundle/ruby/1.9.1/gems/activesupport-3.0.17/lib/active_support/core_ext/string/output_safety.rb:121:in `concat'

  ERROR: Failed to generate exception summary:

  ActionView::Template::Error: incompatible character encodings: ASCII-8BIT and UTF-8

  /home/mangob2b/webapp/releases/20121012180750/vendor/bundle/ruby/1.9.1/gems/activesupport-3.0.17/lib/active_support/core_ext/string/output_safety.rb:121:in `concat'
  /home/mangob2b/webapp/releases/20121012180750/vendor/bundle/ruby/1.9.1/gems/activesupport-3.0.17/lib/active_support/core_ext/string/output_safety.rb:121:in `concat'
  /home/mangob2b/webapp/releases/20121012180750/vendor/bundle/ruby/1.9.1/gems/actionpack-3.0.17/lib/action_view/template/handlers/erb.rb:14:in `<<'
  /home/mangob2b/webapp/releases/20121012180750/vendor/bundle/ruby/1.9.1/gems/exception_notification-3.0.0.rc1/lib/exception_notifier/views/exception_notifier/_request.text.erb:3:in `_vendor_bundle_ruby_______gems_exception_notification_______rc__lib_exception_notifier_views_exception_notifier__request_text_erb___2113842360223233242_103762400_284534257767116840'

I must stress that in my development env i get this warning frequently: 

/usr/local/lib/ruby/gems/1.9.1/gems/activesupport-3.0.17/lib/active_support/core_ext/string/output_safety.rb:23: warning: regexp match /.../n against to UTF-8 string

I use Rails 3.0.17 and Ruby 1.9.3p194

Any clues?

**Comment by san650** [comment] 2015-12-14 21:46
Hi!

I'm doing some bug triage and I would like to know if this bug is still happening on master.

The idea is to close those errors that can't be reproduced or that don't have enough information to reproduce it. I'll revisit this bug in a week and I'll close it if there's no more information. It can be opened again later if necessary.

Thanks!

**Comment by haslinger** [comment] 2015-12-14 23:02
For me, it's definitively gone. (Just recreated the old situation, and I'm sure, I'm fine.)

**Comment by holli** [comment] 2015-12-15 16:52
I tried with newest version (4.1.2) and its still there.

```
ERROR: Failed to generate exception summary:

  ActionView::Template::Error: incompatible character encodings: ASCII-8BIT and UTF-8

.../shared/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/core_ext/string/output_safety.rb:167:in `concat'
.../shared/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/core_ext/string/output_safety.rb:167:in `safe_concat'
.../shared/bundle/ruby/2.2.0/gems/actionview-4.2.3/lib/action_view/buffers.rb:18:in `safe_expr_append='
.../shared/bundle/ruby/2.2.0/gems/exception_notification-4.1.2/lib/exception_notifier/views/exception_notifier/_environment.text.erb:4:in `block in 
```

**Comment by san650** [comment] 2015-12-19 18:42
@holli I've opened #305 with a potential fix based on your suggestions, can you check out the fix?

**Comment by smartinez87** [comment] 2015-12-22 13:47
closing this since #305 got merged.

**Comment by san650** [comment] 2015-12-22 13:48
:tada:  thanks @smartinez87

**Closed by smartinez87** 2015-12-22 13:47 UTC
Labels: bug
